src/assets/sass/_catalog.sass, src/components/App/App.tsx, src/components/Cabinet/CabinetWaitingList/CabinetWaitingListItem.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/ProductBlock/ProductBlock.tsx, src/components/Reglog/ReglogCheckEmail/ReglogCheckEmail.tsx, src/components/WaitingList/WaitingListCreate/WaitingListCreate.tsx, src/components/WaitingList/WaitingListCreate/WaitingListCreateForm.tsx, src/components/WaitingList/WaitingListCreate/WaitingListCreateSuccess.tsx, src/components/WaitingList/WaitingListCreate/validate.ts, src/components/WaitingList/WaitingListDelete/WaitingListDelete.tsx, src/components/WaitingList/WaitingListDelete/WaitingListDeleteConfirm.tsx, src/components/index.ts, src/constants/catalog.ts, src/constants/keys.ts, src/functions/getCatalogFiltersUrl.ts, src/redux/actions/waiting.ts
https://www.notion.so/WaitingList-6dcae3f5cc8e496292682652c947d705?pvs=4
=> feature/1503: added waiting list create/delete forms

src/app/exchange/page.tsx, src/assets/sass/_variables.sass, src/screens/Exchange/Exchange.tsx, src/screens/index.ts
https://www.notion.so/Exchange-3e86f7dd9aee4d7ea4224e11ac9a5715?pvs=4
=> feature/1494: added exchange page

src/app/brands/page.tsx, src/components/Brands/BrandsList/BrandsList.tsx, src/components/Brands/BrandsList/BrandsListBlock.tsx, src/components/Brands/BrandsSearch.tsx, src/components/index.ts, src/screens/Brands/Brands.tsx, src/screens/Cabinet/CabinetWaitingList.tsx, src/screens/index.ts
https://www.notion.so/Brands-4cad16eeb6b049c28198763cb64bc613?pvs=4
=> feature/1487: added brands page

src/app/about/page.tsx, src/screens/About/About.tsx, src/screens/index.ts
https://www.notion.so/About-49843771bc1147eeb009654b4551f6ec?pvs=4
=> feature/1484: added about page

.vscode/settings.json, src/app/AlionaDoletskaya/page.tsx, src/components/AlyonaDoletskaya/AlyonaDoletskayaProductSection/AlyonaDoletskayaProductSection.tsx, src/components/Header/HeaderMedia/HeaderMedia.tsx, src/components/index.ts, src/screens/AlyonaDoletskaya/AlyonaDoletskaya.tsx, src/screens/index.ts
https://www.notion.so/AlyonaDoletskaya-f96c6d720a29482e93fd5010e0c245da?pvs=4
=> feature/1485: added AlionaDoletskaya page

src/app/favorites/[userId]/page.tsx, src/screens/PublicFavorites/PublicFavorites.tsx, src/screens/index.ts
https://www.notion.so/PublicFavorites-588f2a0c3d8b4e84b19fff0ea279c0c9?pvs=4
=> feature/1498: added public favorites page

src/app/contact/page.tsx, src/assets/sass/_contact.sass, src/constants/contacts.ts, src/constants/routes.ts, src/screens/Contact/Contact.tsx, src/screens/index.ts
https://www.notion.so/Contact-9919b0ed15ba43b4873e39c139bb9da9?pvs=4
=> feature/1493: added contacts page

src/app/cart/page.tsx, src/components/Cart/CartItemBlock.tsx, src/components/index.ts, src/screens/Cart/Cart.tsx, src/screens/index.ts
https://www.notion.so/Cart-397adabdd8584b9d95add5e30bf117d9?pvs=4
=> feature/1490: added cart page

src/app/layout.tsx, src/app/order/[id]/page.tsx, src/app/order/page.tsx, src/assets/sass/_interface.sass, src/assets/sass/_order.sass, src/components/AlyonaDoletskaya/AlyonaDoletskayaProductSection/AlyonaDoletskayaProductSection.tsx, src/components/Header/HeaderCart/HeaderCartModal.tsx, src/components/Header/HeaderCart/HeaderCartModalAddMessage.tsx, src/components/Order/OrderForm/OrderForm.tsx, src/components/Order/OrderForm/OrderFormAddress.tsx, src/components/Order/OrderForm/OrderFormContact.tsx, src/components/Order/OrderForm/OrderFormCountry.tsx, src/components/Order/OrderForm/OrderFormDelivery.tsx, src/components/Order/OrderForm/OrderFormPayments.tsx, src/components/Order/OrderForm/validate.ts, src/components/Order/OrderProducts/OrderProducts.tsx, src/components/Order/OrderProducts/OrderProductsItem.tsx, src/components/Order/OrderProducts/OrderProductsPromocode.tsx, src/components/Order/OrderStatus/OrderStatusError.tsx, src/components/Order/OrderStatus/OrderStatusProduct.tsx, src/components/Order/OrderStatus/OrderStatusSuccess.tsx, src/components/Order/orderPay.ts, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitleSplit/ProductInfoTitleSplitPopup.tsx, src/components/UI/RenderCheckbox.tsx, src/components/index.ts, src/constants/validation.ts, src/redux/actions/order.ts, src/screens/Order/Order.tsx, src/screens/OrderDetails/OrderDetails.tsx, src/screens/index.ts
https://www.notion.so/3852f28bfcab4440a47de101229717fc?v=d7fdd6e0d5e745b98b2d88ad8c80a72f&p=8804d10814a14b78b15889cebd43d40c&pm=c
=> feature/1496: Добавил Ордер

next.config.mjs, package-lock.json, package.json, src/assets/sass/_interface.sass, src/assets/sass/_sell_info.sass, src/components/Footer/Footer.tsx, src/components/Header/Header.tsx, src/components/Header/HeaderMedia/HeaderMedia.tsx, src/components/Product/ProductExchange.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitleSplit/ProductInfoTitleSplitPopup.tsx, src/components/Selections/SelectionSliderCard/SelectionSliderCard.tsx, src/components/SellInfo/SellInfoMain.tsx, src/components/SellInfo/SellInfoService.tsx, src/components/SellInfo/SellInfoSteps.tsx, src/components/UI/BaseImage/BaseImage.tsx, src/components/index.ts, src/screens/About/About.tsx, src/screens/Exchange/Exchange.tsx, src/screens/NotFound/NotFound.tsx
https://www.notion.so/img-Next-Image-c6afdd66bd804a77aeaabd30411a1579?pvs=4
=> feature/1515: added next image

src/assets/sass/_sell.sass, src/components/Sell/SellCooperation/SellCooperation.tsx, src/screens/SellCreate/SellCreate.tsx
https://www.notion.so/VIP-0381d7c2bc634a5d8174597b699cddb1?pvs=4
=> feature/1602: updated vip service card on sell page

src/components/Product/ProductCard/ProductCardImages.tsx, src/components/Product/ProductCard/styles.sass
https://www.notion.so/165f04bcaf29425fb83abe6df0a22dd2?pvs=4
=> feature/1657: fix product card images

src/assets/sass/_public_favorites.sass, src/components/AlyonaDoletskaya/AlyonaDoletskayaProductSection/AlyonaDoletskayaProductSection.tsx, src/components/Catalog/CatalogProducts/CatalogProductsSection.tsx, src/components/Header/HeaderSearchBox/HeaderSearchBox.tsx, src/components/Product/ProductCard/ProductCard.tsx, src/components/Product/ProductCard/ProductCardImages.tsx, src/components/Product/ProductCard/styles.sass, src/redux/reducers/favorites.ts, src/redux/reducers/public_favorites.ts, src/screens/Cabinet/CabinetFavorites.tsx, src/screens/PublicFavorites/PublicFavorites.tsx
https://www.notion.so/56524bd16528451fb7bce6eeee9ffff8?pvs=4
=> feature/1655: added new product cards

src/components/Cabinet/CabinetSetting/CabinetSettingInfoBlock/CabinetSettingInfoBlock.tsx, src/components/Catalog/CatalogFilters/CatalogFilters.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersBlockWrapper.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersBrands.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersColors.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersConditions.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersGlassFrame.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersModels.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersSelections.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersSex.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersSize.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersTypes.tsx, src/components/Catalog/CatalogFiltersTop/CatalogFiltersTop.tsx, src/components/UI/RenderInputHints.tsx, src/components/WaitingList/WaitingListCreate/WaitingListCreateForm.tsx, src/constants/catalog.ts, src/models/IProductFilters.ts, src/redux/actions/products_filters.ts, src/redux/reducers/products_filters.ts, src/redux/reducers/user.ts, src/redux/types/IProductsFilters.ts, src/screens/Cabinet/CabinetSetting.tsx, src/types/catalog.ts
https://www.notion.so/slugs-c49e92b38bec40cb83f0b753c25910bb?pvs=4
=> fix/1678: catalog filters fixes

src/components/Order/OrderProducts/OrderProducts.tsx, src/redux/actions/cart.ts, src/redux/actions/favorites.ts
https://www.notion.so/2-1-ff62076305ec40a1a00ab5e996b8cd20?pvs=4
https://www.notion.so/2-6-f59f8dffa7d0464b82060005f488a1dd?pvs=4
=> fix/1462: mindbox fixes - ClearCart, SetWishList

src/assets/sass/_product.sass, src/components/Product/ProductCard/ProductCard.tsx, src/components/Product/ProductCard/styles.sass, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitleSplit/ProductInfoTitleSplit.tsx, src/http/index.ts
https://www.notion.so/cd46321932694795a4c6448876df7e25?pvs=4
=> fix/1686: product details page fixes

src/components/Header/Header.tsx
https://www.notion.so/Tiffany-Co-0fc1afed5f6240459238119bbf34fa32?pvs=4
=> fix/1701: fixed brand name Tiffany & Co.

src/components/Product/ProductCard/ProductCardBadges.tsx, src/components/Product/ProductCard/ProductCardFavorites.tsx
https://www.notion.so/d5ba24e78bb148029fedc10d5d057979?pvs=4
=> feature/1298: hides zero likes

src/components/Cabinet/CabinetSetting/CabinetSettingInfoBlock/CabinetSettingInfoBlock.tsx, src/components/Catalog/CatalogFilters/CatalogFilters.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersBlockWrapper.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersBrands.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersColors.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersConditions.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersGlassFrame.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersModels.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersSelections.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersSex.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersSize.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersTypes.tsx, src/components/Catalog/CatalogFiltersTop/CatalogFiltersTop.tsx, src/components/UI/RenderInputHints.tsx, src/components/WaitingList/WaitingListCreate/WaitingListCreateForm.tsx, src/constants/catalog.ts, src/models/IProductFilters.ts, src/redux/actions/products_filters.ts, src/redux/reducers/products_filters.ts, src/redux/reducers/user.ts, src/redux/types/IProductsFilters.ts, src/screens/Cabinet/CabinetSetting.tsx, src/types/catalog.ts
=> new/fix/1678: Fix catalog for slugs

src/components/Brands/BrandsList/BrandsList.tsx, src/components/Brands/BrandsList/BrandsListBlock.tsx, src/redux/actions/brands.ts, src/redux/reducers/brands.ts, src/redux/types/IBrands.ts
=> feature/1694: fix brands page for slugs

src/components/Catalog/CatalogFilters/CatalogFiltersBlockWrapper.tsx
https://www.notion.so/GIF-dad838d28c6d4b1c8eac2659a5d4cb70?pvs=4
=> feature/917: todo animated opening catalog filters

src/assets/sass/_header_search_box.sass, src/assets/sass/_interface.sass, src/assets/sass/_product.sass, src/components/Header/HeaderSearchBox/HeaderSearchBox.tsx, src/components/Order/OrderForm/OrderFormPayments.tsx, src/components/Product/ProductInfo/ProductInfo.tsx, src/components/Product/ProductInfo/ProductInfoConcierge/ProductInfoConcierge.tsx, src/components/Product/ProductInfo/ProductInfoConcierge/ProductInfoConciergeForm.tsx, src/components/Product/ProductInfo/ProductInfoConcierge/validate.ts, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitleSplit/ProductInfoTitleSplit.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitleSplit/ProductInfoTitleSplitPopup.tsx, src/components/UI/RenderRadioSelect.tsx, src/components/index.ts, src/constants/app.ts, src/constants/order.ts, src/constants/routes.ts, src/hooks/catalog/useCatalogFilters.ts, src/hooks/catalog/useCatalogFiltersTitle.ts, src/redux/actions/concierge.ts, src/redux/actions/products.ts
https://www.notion.so/3852f28bfcab4440a47de101229717fc?v=d7fdd6e0d5e745b98b2d88ad8c80a72f&p=461d9af2257e4f8b93bab73781b95d72&pm=c
=> Feature/1730: Консьерж. Подсветить в разных точках флоу

src/components/Catalog/CatalogBanner/CatalogBanner.tsx, src/components/Catalog/CatalogBannerMedia/CatalogBannerMedia.tsx
https://www.notion.so/b48e0240d6a94bebacd1e055d22f9172
=> feature/1725: Экстра-мера августа: Баннер Консьержа в сумках и украшениях

package-lock.json, package.json, src/assets/sass/_order.sass, src/components/Cabinet/CabinetHistoryOrders/CabinetHistoryOrdersItem.tsx, src/components/Order/OrderStatus/OrderStatusError.tsx, src/constants/order.ts
https://www.notion.so/3852f28bfcab4440a47de101229717fc?v=d7fdd6e0d5e745b98b2d88ad8c80a72f&p=95af0b77f1e249f6a7ed61a6f9737a3e&pm=c
=> feature/1664: Таймер во время оплаты 

src/components/Cabinet/CabinetSellsList/CabinetSellsListPaymentInfo/CabinetSellsListPaymentInfoPopupForm.tsx, src/components/Cabinet/CabinetSetting/CabinetSettingPaymentBlock/CabinetSettingPaymentBlock.tsx
https://www.notion.so/3852f28bfcab4440a47de101229717fc?v=d7fdd6e0d5e745b98b2d88ad8c80a72f&p=efcd029270da48d292275752951f3944&pm=c
=> feature/596: Добавить маски в форму заполнения реквизитов (ЛК Продавца)

src/assets/sass/_header_search_box.sass, src/components/Header/HeaderSearchBox/HeaderSearchBox.tsx
https://www.notion.so/3852f28bfcab4440a47de101229717fc?v=d7fdd6e0d5e745b98b2d88ad8c80a72f&p=654ec054b156423eac6d823eabe8457e&pm=c
=> feature/909: Улучшение “Поиска”

src/components/Header/HeaderMedia/HeaderMediaModalMenu.tsx, src/components/Home/HomeCategories/HomeCategories.tsx, src/components/Home/HomeCategories/HomeCategoriesItem.tsx, src/components/Home/HomeCategories/constants.ts, src/components/Home/HomeMainBanner/constants.tsx, src/components/Product/ProductInfo/ProductInfoBreadCrumbs.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/SellInfo/SellInfoCategories.tsx, src/constants/catalog.ts, src/screens/Home/Home.tsx
https://www.notion.so/be8144392f3a478985da6c77c4d718ac?pvs=4
=> Fix/1745: fix catalog links

src/components/Cart/CartProductItem/CartProductItem.tsx, src/components/Order/OrderProducts/OrderProducts.tsx, src/constants/routes.ts, src/redux/actions/cart.ts, src/redux/reducers/cart.ts, src/redux/types/ICart.ts
https://www.notion.so/c2da0b2058eb4b93abd80938eba80bd0?pvs=4
=> feature/1744: fix order checked cart products + fixes

src/assets/sass/_product.sass, src/components/Product/ProductCover.tsx
https://www.notion.so/7a3735af841e4043a46b642700aa9dca?pvs=4
=> fix/1746: fixed product page images slider

src/assets/sass/_cart.sass, src/assets/sass/_header_cart.sass, src/components/App/App.tsx, src/components/Cart/CartList/CartList.tsx, src/components/Cart/CartList/styles.sass, src/components/Cart/CartProductItem/CartProductItem.tsx, src/components/Header/HeaderCart/HeaderCart.tsx, src/components/Header/HeaderCart/HeaderCartModal.tsx, src/components/Header/HeaderCart/HeaderCartModalAddMessage.tsx, src/components/Header/HeaderMedia/HeaderMedia.tsx, src/components/Order/OrderForm/OrderFormPayments.tsx, src/components/Order/OrderProducts/OrderProducts.tsx, src/components/Order/OrderStatus/OrderStatusError.tsx, src/components/Product/ProductCover.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/index.ts, src/functions/getClassNames.ts, src/functions/getUrlWithParams.ts, src/hooks/catalog/useCart.ts, src/models/ICartItem.ts, src/models/IProduct.ts, src/redux/actions/cart.ts, src/redux/reducers/products.ts, src/screens/Cart/Cart.tsx, src/screens/Order/Order.tsx
https://www.notion.so/a666b0a2c23648aca8e59ef886b90710?pvs=4
=> Feature/1750: jewelry cart

src/components/Order/OrderForm/OrderForm.tsx, src/components/Order/OrderForm/OrderFormContact.tsx, src/components/Order/OrderForm/OrderFormPayments.tsx, src/components/Order/OrderForm/validate.ts, src/components/Order/OrderProducts/OrderProducts.tsx, src/components/Order/OrderStatus/OrderStatusError.tsx, src/constants/app.ts, src/constants/validation.ts, src/hooks/order/useOrder.ts, src/redux/actions/order.ts, src/screens/Order/Order.tsx
https://www.notion.so/e35e6c75570746259975bab797b0741b?pvs=4
=> Feature/1751: jewelry checkout updates

src/components/Catalog/CatalogFilters/CatalogFiltersSelections.tsx, src/components/Header/Header.tsx, src/functions/getDefaultPageSort.ts, src/hooks/catalog/useCatalogFilters.ts, src/hooks/catalog/useCatalogFiltersTitle.ts, src/hooks/catalog/useCatalogScroll.ts, src/hooks/catalog/useWaitingData.ts, src/redux/reducers/selections.ts
https://www.notion.so/164bf43b356a4a02a41cb3d598966375?pvs=4
=> fix/1796: fixed selections

src/assets/sass/_sell.sass, src/components/Sell/SellDelivery/SellDelivery.tsx, src/redux/reducers/cabinet_sell.ts
https://faceted-utahraptor-478.notion.site/76236b2d9dc34dcf9ad72e36f9f69401?pvs=4
=> feature/1755: Ювелирка. Продавец. Способ отправки

src/components/UI/Button/Button.tsx, src/components/UI/Button/styles.sass, src/components/index.ts
https://www.notion.so/theculttcom/UI-KIT-Button-4b10fce3c9514e1ab1cdd2c5a65928df?pvs=4
=> feature/1809: todo button ui component

src/components/UI/Textarea/Textarea.tsx, src/components/UI/Textarea/styles.sass, src/components/formik/FormikTextarea/FormikTextarea.tsx, src/components/index.ts, src/types/ui.ts
https://www.notion.so/theculttcom/UI-KIT-Textarea-7cca925376bf48bda5dbb86e97428a42?pvs=4
=> feature/1834: todo new textarea components

src/assets/icons/check.svg, src/assets/icons/chevron-down.svg, src/assets/icons/index.ts, src/components/UI/Input/Input.tsx, src/components/UI/Input/styles.sass, src/components/UI/Select/Option.tsx, src/components/UI/Select/Select.tsx, src/components/UI/Select/styles.sass, src/components/formik/FormikInput/FormikInput.tsx, src/components/formik/FormikSelect/FormikSelect.tsx, src/components/formik/FormikTextarea/FormikTextarea.tsx, src/components/index.ts, src/types/ui.ts
https://www.notion.so/theculttcom/UI-KIT-Select-1ccfe73c8c7c4868b35d9f12821c164d?pvs=4
=> Feature/1808: todo ui select component

src/assets/icons/check.svg, src/assets/icons/chevron-down.svg, src/assets/icons/index.ts, src/components/UI/Input/Input.tsx, src/components/UI/Input/styles.sass, src/components/UI/Select/Option.tsx, src/components/UI/Select/Select.tsx, src/components/UI/Select/styles.sass, src/components/formik/FormikInput/FormikInput.tsx, src/components/formik/FormikSelect/FormikSelect.tsx, src/components/formik/FormikTextarea/FormikTextarea.tsx, src/components/index.ts, src/types/ui.ts
https://www.notion.so/theculttcom/UI-KIT-Select-1ccfe73c8c7c4868b35d9f12821c164d?pvs=4
=> Feature/1808: ui select

src/components/Catalog/CatalogFilters/CatalogFilters.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersMetalType.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersSize.tsx, src/components/Header/HeaderCart/HeaderCartModalAddMessage.tsx, src/components/Header/HeaderMedia/HeaderMediaModalMenu.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/index.ts, src/constants/catalog.ts, src/functions/capitalize.ts, src/hooks/catalog/useCatalogFilters.ts, src/models/IProductFilters.ts, src/redux/actions/products.ts, src/redux/actions/products_filters.ts, src/redux/reducers/products_filters.ts, src/redux/types/IProductsFilters.ts, src/types/catalog.ts
https://www.notion.so/theculttcom/e6c7ffd1b8fd48309200fb4a12397cc7?pvs=4
=> feature/1763: todo catalog filter by metal type + fixes

src/components/Cabinet/CabinetSetting/CabinetSettingPaymentBlock/CabinetSettingPaymentBlock.tsx, src/redux/actions/user.ts, src/redux/types/IUser.ts, src/screens/Cabinet/CabinetSetting.tsx
https://www.notion.so/theculttcom/6129bc2180fd479cbe9256287dc450b0?pvs=4
=> feature/1795: add new personal fields + fixes

src/components/Product/ProductCard/ProductCardBadges.tsx, src/components/Product/ProductCover.tsx, src/components/Product/ProductInfo/ProductInfo.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitleBoutique/ProductInfoTitleBoutique.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitlePartner/ProductInfoTitlePartner.tsx, src/components/UI/Badge/Badge.tsx, src/components/UI/Popup/Popup.tsx, src/components/UI/Popup/styles.sass, src/screens/Product/Product.tsx
https://www.notion.so/theculttcom/2-0-7171eb12a5264169a83c25c9995765a0?pvs=4
=> feature/1849: update partner tag

src/assets/sass/_order.sass, src/components/Order/OrderForm/OrderFormDelivery.tsx
https://theculttcom.notion.site/df69130a1cc14facb3d029b42427b4a0?pvs=4
=> feature/1840: Инфо о доставке с примеркой для неавторизованных пользователей

src/components/Order/OrderProducts/OrderProducts.tsx, src/components/Order/OrderStatus/OrderStatusError.tsx, src/hooks/order/useOrder.ts, src/redux/actions/cart.ts, src/redux/actions/order.ts, src/screens/Cabinet/CabinetHistoryOrders.tsx
https://www.notion.so/theculttcom/f13f68bc54104f328fa702a520548c5f?pvs=4
=> fix/1861: fixed order cart

src/components/Cabinet/CabinetSetting/CabinetSettingPaymentBlock/CabinetSettingPaymentBlock.tsx
https://www.notion.so/theculttcom/e9dbad6b532248bba19570b7062bbff9?pvs=4
=> fix/1863: updated fields names

src/components/Cart/CartProductItem/CartProductItem.tsx, src/components/Order/OrderForm/OrderFormPayments.tsx, src/components/Product/ProductCard/ProductCard.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/ProductBlock/ProductBlock.tsx, src/models/IProduct.ts
https://www.notion.so/theculttcom/790b5d9797154bbd8d887fd66f0330f8
=> Feature/1865: В корзине ювелире нужно убрать способы оплаты. Оставить только на сайте

src/components/Order/OrderForm/OrderFormContact.tsx, src/constants/keys.ts, src/redux/actions/check_email.ts, src/redux/actions/login.ts, src/redux/reducers/check_email.ts
https://theculttcom.notion.site/8bf70973444c43b083926f9ee4d99d83?pvs=4
Убрал сущность Email в LocalStorage, так как в ней не было смысла
=> feature/1874: Поправить баг с авторизацией в чужой аккаунт + сделать сразу ввод пароля при входе с ордера

src/components/Faq/FaqTheCultt.tsx, src/constants/menu.ts, src/constants/routes.ts
https://www.notion.so/theculttcom/d1d1b8dd5c284f6686e7aa53d21c158e?pvs=4
=> feature/1765: added jewelry docs

src/assets/sass/_sell.sass, src/components/Sell/SellDelivery/SellDelivery.tsx, src/components/Sell/SellInfo/SellInfo.tsx, src/components/Sell/SellSteps.tsx, src/components/UI/RenderSelect.tsx, src/components/UI/RenderSelectArray.tsx, src/constants/sell.ts
https://www.notion.so/theculttcom/ac7e53f323b2455caa8e4b8cc0dc3794?pvs=4
=> fix/1883: sell fixes

src/assets/sass/_header.sass, src/assets/sass/_variables.sass, src/components/Header/HeaderCatalogMenu/HeaderCatalogMenu.tsx, src/components/Header/HeaderCatalogMenu/styles.sass
https://www.notion.so/theculttcom/1b569eb358ff4f0792b183da83d08bb7?pvs=4
=> fix/1891: fixed catalog mega menu

src/app/catalog/[category_slug]/[brand_slug]/page.tsx, src/app/catalog/[category_slug]/page.tsx, src/app/layout.tsx, src/components/Catalog/CatalogFilters/CatalogFilters.tsx, src/components/Catalog/CatalogFilters/CatalogFiltersBrands.tsx, src/components/Header/HeaderCatalogMenu/HeaderCatalogMenu.tsx, src/components/Header/constants.tsx, src/constants/brands.ts, src/constants/fonts.ts, src/constants/meta.ts, src/functions/getCatalogFiltersUrl.ts, src/functions/getUrlWithParams.ts, src/hooks/catalog/useCatalogFiltersTitle.ts
https://www.notion.so/theculttcom/S--f4fb2f085982433b8b46fa5354caa4e2?pvs=4
=> feature/1790: added catalog/category/brand page

src/app/product/[article]/page.tsx, src/components/Product/ProductInfo/ProductInfoBreadCrumbs.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/redux/actions/products.ts, src/redux/reducers/products.ts, src/redux/types/IProducts.ts, src/screens/Product/ClientProduct.tsx, src/screens/Product/Product.tsx, src/screens/Product/ServerProduct.tsx, src/services/api/catalog.ts, src/types/product.ts
https://www.notion.so/theculttcom/ssr-8339b141d3364e4bb1ca4eae54ee7350?pvs=4
=> feature/1884: added ssr for product page

src/app/product/[article]/page.tsx, src/components/Product/ProductInfo/ProductInfoBreadCrumbs.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/redux/actions/products.ts, src/redux/reducers/products.ts, src/redux/types/IProducts.ts, src/screens/Product/ClientProduct.tsx, src/screens/Product/Product.tsx, src/screens/Product/ServerProduct.tsx, src/services/api/catalog.ts, src/types/product.ts
https://www.notion.so/theculttcom/ssr-8339b141d3364e4bb1ca4eae54ee7350?pvs=4
=> feature/1884: added ssr for product page + fixes

src/app/brands/[brand_slug]/page.tsx, src/app/catalog/[category_slug]/[brand_slug]/page.tsx, src/app/catalog/[category_slug]/page.tsx, src/app/catalog/page.tsx, src/app/product/[article]/page.tsx, src/app/selections/[selection_id]/page.tsx, src/components/Product/ProductInfo/ProductInfo.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitle.tsx, src/components/Product/ProductInfo/ProductInfoTitle/ProductInfoTitleFavorites.tsx, src/models/IProduct.ts, src/redux/actions/brands.ts, src/redux/actions/cart.ts, src/redux/actions/products.ts, src/redux/actions/selections.ts, src/screens/Catalog/Catalog.tsx, src/screens/Catalog/ClientCatalog.tsx, src/screens/Catalog/ServerCatalog.tsx, src/screens/Product/ServerProduct.tsx, src/services/api/brands.ts, src/services/api/catalog.ts, src/services/api/selections.ts
https://www.notion.so/theculttcom/SEO-catalog-product-9ab38c0c721342a985112faf82e42e80?pvs=4
=> fix/1920: catalog/product fixes

src/functions/getDefaultPageSort.ts, src/functions/parseCatalogSearchParams.ts, src/hooks/catalog/useCatalogFilters.ts, src/services/api/catalog.ts
https://www.notion.so/theculttcom/f5ab0fc4992940b89db839353d64a7a3?pvs=4
=> feature/1927: updated catalog sorts

src/app/sitemap.ts, src/redux/actions/products_filters.ts, src/services/api/catalog.ts
https://www.notion.so/theculttcom/Sitemap-69f0debf20b5493caf908bba899ec3ae?pvs=4
=> feature/1932: added sitemap

src/components/Catalog/CatalogProductsSection/CatalogProductsSection.tsx, src/components/Home/HomeNewProducts/HomeNewProducts.tsx, src/components/Product/ProductRecommendations/ProductRecommendations.tsx, src/components/Reglog/ReglogRegister/ReglogRegister.tsx, src/components/index.ts, src/redux/reducers.ts, src/redux/slices/catalog/asyncActions.ts, src/redux/slices/catalog/selectors.ts, src/redux/slices/catalog/slice.ts, src/redux/slices/catalog/types.ts, src/screens/Home/Home.tsx, src/screens/Product/ClientProduct.tsx
https://www.notion.so/theculttcom/5e1a38ee6d854a64a359695320f0153e?pvs=4
=> fix/1937: fixed new products on main page

src/components/Order/OrderForm/OrderForm.tsx, src/components/Order/OrderForm/OrderFormDelivery.tsx, src/components/Order/OrderForm/validate.ts, src/components/Order/OrderProducts/OrderProducts.tsx, src/constants/delivery.ts, src/redux/actions/order.ts
https://www.notion.so/theculttcom/1-0-341e670f40744d15acdc4c23182804e2?pvs=4
=> feature/1956: added order autocomplete

src/components/Concierge/ConciergeMain/ConciergeMainApplication/ConciergeMainApplication.tsx, src/components/Concierge/ConciergeMain/ConciergeMainApplication/ConciergeMainApplicationForm.tsx, src/components/Concierge/ConciergeMain/ConciergeMainApplication/validate.ts, src/components/Concierge/ConciergeProduct/ConciergeProductForm.tsx, src/components/Concierge/ConciergeProduct/validate.ts, src/constants/validation.ts, src/redux/actions/concierge.ts, src/screens/Concierge/ConciergeMain.tsx, src/screens/Concierge/ConciergeProduct.tsx, src/shared/ui/Textarea/Textarea.tsx
https://www.notion.so/theculttcom/ac5e60b9330f4d47ba57e5869185b276?pvs=4
=> feature/1935: updated concierge product forms

src/assets/sass/_cabinet_setting.sass, src/components/Cabinet/CabinetSetting/CabinetSettingForm/CabinetSettingFormAddress/CabinetSettingFormAddress.tsx, src/components/Cabinet/CabinetSetting/CabinetSettingForm/CabinetSettingFormAddress/constants.ts, src/components/Cabinet/CabinetSetting/CabinetSettingForm/CabinetSettingFormAddress/validate.ts, src/components/Cabinet/CabinetSetting/CabinetSettingForm/CabinetSettingFormContact/CabinetSettingFormContact.tsx, src/components/Cabinet/CabinetSetting/CabinetSettingForm/CabinetSettingFormEditButtons.tsx, src/components/Cabinet/CabinetSetting/CabinetSettingForm/CabinetSettingFormInfo/CabinetSettingFormInfo.tsx, src/components/Cabinet/CabinetSetting/CabinetSettingForm/CabinetSettingFormPayment/CabinetSettingFormPayment.tsx, src/components/Cabinet/CabinetSetting/CabinetSettingForm/types.ts, src/constants/validation.ts, src/hooks/useAuthUser.ts, src/redux/slices/user/asyncActions.ts, src/redux/slices/user/selectors.ts, src/redux/slices/user/slice.ts, src/redux/slices/user/types.ts, src/shared/form/FormikRadio/FormikRadio.tsx, src/shared/ui/Button/styles.sass
https://www.notion.so/theculttcom/60f0a49b7dd24f60b6404306c953df9e?pvs=4
=> fix/1971: profile fixes

src/screens/Order/OrderSidebar/OrderSubmit/OrderSubmit.tsx
https://www.notion.so/theculttcom/3d16fbdccb5a4ce384553594b660e88c?pvs=4
https://www.notion.so/theculttcom/1-0-341e670f40744d15acdc4c23182804e2?pvs=4
=> feature/1956: error scroll fix
